-- Add missing columns to auctions table
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'JPY';
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS bid_increment INTEGER DEFAULT 1000;
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS reserve_price DECIMAL(15,2);
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT 1;
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS condition TEXT;
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS location TEXT DEFAULT 'Tokyo, Japan';
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS shipping_cost DECIMAL(15,2) DEFAULT 2500;
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS shipping_method TEXT;
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS payment_methods TEXT[];
ALTER TABLE auctions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
